macos-sonoma:
  stage: build
  image: registry.gitlab.com/libvirt/libvirt-ci/cirrus-run:latest
  interruptible: true
  needs: []
  script:
    - cirrus-vars <build.yml >sonoma.yml
    - cat sonoma.yml
    - cirrus-run -v --show-build-log always sonoma.yml
  rules:
    - if: '$CIRRUS_GITHUB_REPO == null || $CIRRUS_API_TOKEN == null'
      when: never

    - if: '$CI_PROJECT_NAMESPACE == "nertpinx" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success

    - when: never
